name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge CDN cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/codm-test-server/codm-config.js
